services:
  - type: web
    name: revenue-ripple-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: SUPABASE_URL
        fromEnvVar: SUPABASE_URL
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromEnvVar: SUPABASE_SERVICE_ROLE_KEY
      - key: STRIPE_SECRET_KEY
        fromEnvVar: STRIPE_SECRET_KEY
      - key: STRIPE_WEBHOOK_SECRET
        fromEnvVar: STRIPE_WEBHOOK_SECRET
      - key: GETRESPONSE_API_KEY
        fromEnvVar: GETRESPONSE_API_KEY
      - key: GETRESPONSE_CAMPAIGN_ID
        fromEnvVar: GETRESPONSE_CAMPAIGN_ID 