-- Founders campaign tables and functions

create table if not exists public.founders_campaign (
  id bigint generated by default as identity primary key,
  name text not null default '7-Day Founders Annual Fast Cash Launch',
  cap integer not null default 10,
  sold_count integer not null default 0,
  status text not null default 'active', -- active | sold_out | paused
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

create table if not exists public.founder_members (
  id bigint generated by default as identity primary key,
  email text unique not null,
  badge text not null default 'founder',
  status text not null default 'active',
  created_at timestamp with time zone default now()
);

create table if not exists public.founders_waitlist (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamp with time zone default now()
);

-- Ensure one active campaign exists
insert into public.founders_campaign (cap, sold_count, status)
select 10, 0, 'active'
where not exists (select 1 from public.founders_campaign where status = 'active');

-- Function to increment sold safely and mark sold_out
create or replace function public.increment_founders_sold()
returns void
language plpgsql
as $$
declare
  current_cap integer;
  current_sold integer;
begin
  update public.founders_campaign
  set sold_count = sold_count + 1,
      updated_at = now()
  where id = (
    select id from public.founders_campaign where status = 'active' order by id asc limit 1
  )
  returning cap, sold_count into current_cap, current_sold;

  if current_sold >= current_cap then
    update public.founders_campaign
    set status = 'sold_out', updated_at = now()
    where status = 'active';
  end if;
end;
$$;

-- RLS off by default for server role operations
alter table public.founders_campaign enable row level security;
alter table public.founder_members enable row level security;
alter table public.founders_waitlist enable row level security;

-- Simple RLS: allow anon insert into waitlist; restrict others to auth if needed
do $$ begin
  begin
    create policy waitlist_insert_public on public.founders_waitlist for insert to anon using (true) with check (true);
  exception when duplicate_object then null; end;
end $$;

